### ISSUE TITLE
About the Gromacs installation in ISAMBARD

### ISSUE THREAD

**Issue by xiki-tempula** [gw4-isambard/docs#22]
Dear @jrprice ,
I’m a user of the ISAMBARD and I’m interested in using a plumed patched version of Gromacs. I can see that Gromacs has been installed in ISAMBARD. I wonder if I can have the installation script so that I can install the plumed patched version of Gromacs? Thank you.
Kind regards,
Zhiyi Wu

**Comment by christopheredsall** [comment]
Hi @xiki-tempula , the official mechanism for user support on Isambard is via the [Isambard Support helpdesk](https://gw4-isambard.github.io/docs/user-guide/support.html) where you should find we have now responded,

For completeness, the build script notes are:

```bash
# Built by James Price

wget http://ftp.gromacs.org/pub/gromacs/gromacs-2019.3.tar.gz
88ef44802f4e1b1749d8953e8d11a679

module swap PrgEnv-cray/6.0.5 PrgEnv-gnu
module load cray-fftw/3.3.8.2
# GCC version 8.2.0

PKG_CONFIG_PATH=${FFTW_DIR}/pkgconfig:$PKG_CONFIG_PATH

cmake .. -DCMAKE_INSTALL_PREFIX=/lustre/software/aarch64/apps/gromacs/2019.3 \
      -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=CC \
      -DCMAKE_BUILD_TYPE=Release \
      -DGMX_MPI=ON -DGMX_GPU=OFF -DGMX_DOUBLE=OFF \
      -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \

make
make install
```
