### ISSUE TITLE
Add info for using vtune on relevant parts of phase 1

### ISSUE THREAD

**Issue by james-grant1** [gw4-isambard/docs#50]
vtune use does not appear in user docs
as per support ticket 74 re gui not running on login nodes and response from JPrice:

```I looked into this today (sorry for taking so long!), but it seems like this missing library is tied to the graphics driver, which we don't have on the login nodes. We do have the required drivers on the P100 compute nodes though, so you can `qsub -X -I -q pascalq` and run `amplxe-gui` from there. Is that sufficient for your needs?```

**Comment by heaton-dev** [comment]
I wouldn't recommend using the Pascal compute nodes just to run a GUI! If there are graphics "drivers" missing on the login nodes we can look into this, I must imagine it's just X11, although I'm sure we have this?

**Comment by heaton-dev** [comment]
Looks like this module has bigger problems these days

```
login-01:~> module load intel-parallel-studio-xe/vtune_amplifier_xe/2017/2.0.499904
login-01:~> amplxe-gui
Segmentation fault
```

As this software isn't used, because it can't be, and the software stack has changed a lot since this was opened, I'll close this for now.
