### ISSUE TITLE
venv

### ISSUE THREAD

**Issue by james-grant1** [gw4-isambard/docs#52]
Several tickets including 284 have requested installation of libraries, suggest creating how to guide on creating venvs and installing libraries on the different components might be useful.

**Comment by heaton-dev** [comment]
MACS uses [Red Hat Software Collections Python](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/) which is loaded by default for all users, therefore they only need to follow the normal Python venv process.

i.e. `python3 -m venv my-venv`

XCI has a system version of Python3 but also has modules named `cray-python/3.x.x.x` which would be best to load before following the normal venv process.
