### ISSUE TITLE
Memory on XCI nodes

### ISSUE THREAD

**Issue by james-grant1** [gw4-isambard/docs#64]
User had an OOM issue which occurred due to a difference in inputs for similar jobs causing and increase in the memory requirements from ~220GB to ~290GB.
The jobs ran on low node numbers to weren't directly impacted but if they had been allocated the new nodes nodes with higher memory confusion for the user and diagnosing the issue would have been greater.  At very least we should have clearer advice around this instructions for requesting higher-memory nodes in jobscripts:

```
#PBS -l mem=500GB
```
If this becomes a recurring issue then we could also consider

**Comment by heaton-dev** [comment]
fixed by #90
