### ISSUE TITLE
Typo "IndentityFile" should be "IdentityFile"

### ISSUE THREAD

**Issue by heaton-dev** [gw4-isambard/docs#70]
https://github.com/gw4-isambard/docs/blob/master/user-guide/connecting.rst#L53

Typo is not in the config block so it's not urgent.

**Comment by christopheredsall** [comment]
Fixed by @tomgreen66 in https://github.com/gw4-isambard/docs/commit/68f3586e4505fe718af24eed0a9041f102c9a2a2
