### ISSUE TITLE
Mention GW4 projects in requestaccount.md

### ISSUE THREAD

**Issue by heaton-dev** [gw4-isambard/docs#73]
We refer new users to the list of projects, it would be helpful to list likely projects since the SAFE list is quite long and the project names don't start with the institution name so it's not searchable either.

**Comment by christopheredsall** [comment]
It seems they have recently introduced typeahead searching. All the Isambard projects start with `GW`

![image](https://user-images.githubusercontent.com/1021204/104313671-43a8d180-54d0-11eb-8240-959b28650df7.png)

**Comment by heaton-dev** [comment]
Thanks Chris, I believe this is a browser feature, not a website feature; so not everyone will see that.

This is what I see on Edge:
![image](https://user-images.githubusercontent.com/29301353/104314543-8028fd00-54d1-11eb-94c5-47de974608fc.png)

This particular example isn't very helpful since it doesn't show the longname of the project. Not sure if this is because we're on different pages, but in that case if SAFE's dropdowns aren't consistent then we'd still want to specify the shortnames in the user docs
